#ifndef ULTIMATE_G
# define ULTIMATE_G
# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <fcntl.h>
# include <math.h>
# include <string.h>
# include <stdarg.h>
# include <limits.h>
# include <sys/types.h>
# include <sys/uio.h>
# include <sys/stat.h>
# include <errno.h>
# include "libft/libft.h"
# include "printf/includes/ft_printf.h"
# include "gnl/get_next_line.h"
# include "garbage_collector/include/garbage_collector.h"
# include "garbage_descriptor/include/garbage_descriptor.h"
#endif // !ULTIMATE_G